### ISSUE TITLE
readthedocs documentation

### ISSUE THREAD

**Issue by azmeuk** [cguardia/ZODB-Documentation#19]
Hi.
This documentation is published under the URL https://zodb.readthedocs.io but this is quite confusing since the URL suggests this is the official ZODB documentation.

Would you accept to move https://zodb.readthedocs.io to another URL, say https://zodb-book.readthedocs.io?
That would allow me to publish the documentation from https://github.com/zopefoundation/ZODB at https://zodb.readthedocs.io 

@cguardia  What do you think?

Éloi

**Comment by icemac** [comment]
I'd second the suggestion.

**Comment by azmeuk** [comment]
@icemac I emailed @cguardia and he added both of us as readthedocs admin for `zodb`.
Thank you @cguardia
